pipeline {
    agent any 

    environment {
        TOOL_DIR = "${WORKSPACE}\\Test\\CI_tools"
    }

    stages {
        stage('Build') { 
            steps {
                bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Test\\Debug Debug all"
                bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Test\\Release Release all"
            }
        }

        stage('Static Code Analysis') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat "${TOOL_DIR}\\static-analysis.bat ${WORKSPACE}\\Test"
                }
            }
        }

        stage('Flash-Debug-Image') { 
            steps {
                bat "${TOOL_DIR}\\flash.bat $params.DUT_STLINK_sn ${WORKSPACE}\\Test\\Debug\\Test.bin"
            }
        }

        stage('Flash-Release-Image') { 
            steps {
                bat "${TOOL_DIR}\\flash.bat $params.DUT_STLINK_sn ${WORKSPACE}\\Test\\Release\\Test.bin"
            }
        }

    }

    post {
        success {
            script {
                emailext (
                    to: '${DEFAULT_RECIPIENTS}',
                    subject: "${env.JOB_NAME} Successful build ${env.BUILD_ID}",
                    body: """Build ${env.BUILD_ID} has result ${currentBuild.currentResult}
Find the results In ${env.BUILD_URL}"""
                )
            }
        }
        unsuccessful {
            script {
                emailext (
                    to: '${DEFAULT_RECIPIENTS}',
                    subject: "${env.JOB_NAME} Unsuccessful build ${env.BUILD_ID}",
                    body: """Build ${env.BUILD_ID} has result ${currentBuild.currentResult}
Find the results In ${env.BUILD_URL}"""
                )
            }
        }
    }
}
