pipeline {
    agent any 

    environment {
        TOOL_DIR = "${WORKSPACE}\\Test\\CI_tools"
    }

    stages {
        stage('Build') { 
            steps {
                bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Test\\Debug Debug all"
                bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Test\\Release Release all"
            }
        }

        stage('Static Code Analysis') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat "${TOOL_DIR}\\static-analysis.bat ${WORKSPACE}\\Test"
                }
            }
        }

        stage('Flash-Debug-Image') { 
            steps {
                bat "${TOOL_DIR}\\flash.bat $params.DUT_STLINK_sn ${WORKSPACE}\\Test\\Debug\\Test.bin"
            }
        }

        stage('Flash-Release-Image') { 
            steps {
                bat "${TOOL_DIR}\\flash.bat $params.DUT_STLINK_sn ${WORKSPACE}\\Test\\Release\\Test.bin"
            }
        }

    }

    post {
        success {
            script {
                emailext (
                    to: '${DEFAULT_RECIPIENTS}',
                    subject: "CI_Test - Build # ${env.BUILD_ID} - ${currentBuild.currentResult}!",
                    body: """CI_Test - Build # <strong>${env.BUILD_ID}</strong> - ${currentBuild.currentResult}.<br/>
<br/>
Check console <a href="${env.BUILD_URL}">output</a> to view full results.<br/>"""
                )
            }
        }
        unsuccessful {
            script {
                emailext (
                    to: '${DEFAULT_RECIPIENTS}',
                    subject: "CI_Test - Build # ${env.BUILD_ID} - ${currentBuild.currentResult}!",
                    body: """CI_Test - Build # <strong>${env.BUILD_ID}</strong> - ${currentBuild.currentResult}.<br/>
<br/>
Check console <a href="${env.BUILD_URL}">output</a> to view full results.<br/>"""
                )
            }
        }
    }
}
